version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name CICDCodeDeploy --s3-location s3://webservercicd202410/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src